### ISSUE TITLE
Uncaught exception when using two flips with the same probability

### ISSUE THREAD

**Issue by meettaraviya** [SHoltzen/dice#15]
The program raises an uncaught exception when the following is compiled:
```
let a = flip 0.3 in 
let b = flip 0.3 in
let tmp = observe a || b in
a

```

This is because flip variables are named after their probabilities and we are using `Hashtbl.Poly.add_exn` which raises an exception if we insert a duplicate key.

**Comment by SHoltzen** [comment]
Resolved by Commit dfdcffe881f9e458e5c8eb1115c05c5f4401b209
