### ISSUE TITLE
Incorrect column number in error messages

### ISSUE THREAD

**Issue by qsctr** [SHoltzen/dice#38]
Right now the code outputs `pos_cnum` as the column number but it is actually the offset from the start of the file to that point. Instead we should use `pos_cnum - pos_bol` to get the actual column number ([OCaml docs](https://ocaml.org/releases/4.11/htmlman/libref/Lexing.html)).

**Comment by SHoltzen** [comment]
Great, I was wondering about this, thanks for finding this. I will resolve.
