### ISSUE TITLE
Adding automatic CI for running tests

### ISSUE THREAD

**Issue by mattxwang** [SHoltzen/dice#55]
I think it would be helpful to have a GitHub Actions CI to automatically run `dune test` (and/or `dune exec dicebench`) on every pull request/commit to `master` - it may make development and accepting external contributions easier! 

If this is a good idea, I would be happy to contribute this - let me know what you all think!

**Comment by SHoltzen** [comment]
Hi Matt,

That would be great, thanks for your contribution! What is your proposal for doing this? Are you planning to use GitHub actions?

Steven

**Comment by mattxwang** [comment]
> What is your proposal for doing this? Are you planning to use GitHub actions?

Yes, I think a plan would be to add a single build/test CI action that loads both the required OCaml and Rust environments for dice, and then run `dune build && dune test` - I'm working on a draft in my fork but have hit a snag. Just to confirm, does this sound reasonable to you/do you have any feedback?
