### ISSUE TITLE
Building error to start

### ISSUE THREAD

**Issue by SEICS** [SHoltzen/dice#57]
Hi,

##### I would like to use dice to implement my undergraduate project. However, when I finished setting up the opam and tried to use dune build commands, I have the following error:

----------------------------------------------------------------------------------
Error: _build/default/rsdd/target/release/librsdd.so: No such file or
directory
-----------------------------------------------------------------------------------

##### Can anyone help me with this? Any help would be appreciated!

**Comment by SEICS** [comment]
Solved by reinstalling dice on ubuntu virtual. Seems that rust package has problems installing on mac when building from source and related dependency clap cannot be installed.

**Comment by SHoltzen** [comment]
Glad this was resolved! Sorry for the lack of response.

Yes, building on Ubuntu is the recommended way to build dice at the moment -- we are working to bring back Mac support.
