### ISSUE TITLE
Cannot run on macos

### ISSUE THREAD

**Issue by amirsh** [SHoltzen/dice#61]
When trying to run the most recent version on macos, I've faced the following issues, the solutions of which are reported below them:

1) The most recent version of the package yosjon doesn't work with DICE. Use another version (e.g., 1.6.0).
2) The `rsdd` library doesn't build due to a missing package (`quickersort`). Using the master branch for it works fine.

**Comment by SHoltzen** [comment]
Apologies for the huge delay here. This should be fixed in the latest version.
